name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_DOCKER }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md
            org.opencontainers.image.version=${{ github.event.release.tag_name }}
            org.opencontainers.image.vendor=${{ github.actor }}
            org.opencontainers.image.title=normantle
            org.opencontainers.image.description=The normantle backend
          tags: |
            ghcr.io/lblend/normantle:latest
            ghcr.io/lblend/normantle:${{ github.event.release.tag_name }}
